SU_ITEMS = [
    'The Xiphos',
    "Kraken's Cutlass",
    'Saber of the Stormsail',
    'Aeterna',
    'The Defender',
    'Aurumvorax',
    'Durandal the Blazing Sword',
    "Qarak's Will",
    "Tylwulf's Betrayal",
    'Blacktongue',
    'Feltongue',
    'Shadowsabre',
    'Grotesque Bite',
    'The Captain',
    'Nimmenjuushin',
    "Hephasto's Reaver",
    'Elder Law',
    'Malus Domestica',
    'Dreamflange',
    'Firequeen',
    'Stormpick',
    'Viper Mandate',
    'Legion',
    "Dead Lake's Lady",
    'Thunderbane',
    'Screaming Serpent',
    "Night's Embrace",
    'Lancea',
    'Steel Pillar',
    'Darkspite',
    'The Pride of Caldeum',
    'Bitter Harvest',
    'Bone Scalpel',
    'Frostneedle',
    'Plunderbird',
    "Meshif's Iron Parrot",
    'Warshrike',
    'Buzzbomb',
    'Lacerator',
    'Griefbringer',
    "Vizjerei's Folly",
    'Shamanka',
    'Aerin Nexus',
    "Xorine's Cane",
    'Spire of Kehjan',
    'Chillstring',
    'Gjallarhorn',
    'Stormstrike',
    'Fleshstinger',
    'Hellreach',
    'Ratbane',
    "Nihlathak's Bombard",
    'Horned Hunter',
    'Askarbydd',
    'Luminescence',
    "Serenthia's Scorn",
    'Hellrain',
    'Dreamweaver',
    'Twin Terrors',
    'Implement V.II',
    'Legio Di Manes',
    "Zular Khan's Tempest",
    'Frysturgard',
    'Kaskara of the Taan',
    'Talic the Unwilling',
    'Claw of the Spirit Wolf',
    'Esubane',
    "Skeld's Battlesong",
    'Cleaver of Mirrors',
    'Peace Warder',
    "Ord Rekar's Testament",
    "Yaggai's Sagaris",
    'Faerie Pyre',
    "Azgar's Mark",
    'Guardian of Scosglen',
    'Hanfod Tan',
    'Iron Shard',
    "Reaper's Hand",
    "Karybdus' Descent",
    'Dreamflayer',
    'Mente Scura',
    "Hwanin's Hwacha",
    "Nymyr's Shadow",
    'Grim Visor',
    'Manastorm',
    'Storm Focus',
    "King's Desire",
    "Mad King's Spine",
    'Darkfeast',
    'Herald of Pestilence',
    'Chober Chaber',
    'In Fero Salva',
    'Black Sun Spear',
    "Habacalva's Legacy",
    'Ghostmoon',
    'Bane of the Horadrim',
    'Gravetalon',
    "Leah's Vision",
    'Starhawk',
    "Screen of Viz-Jaq'Taar",
    'Razorspine',
    "Hratli's Craft",
    'Alchemist Apron',
    "Hepsheeba's Mantle",
    'Candlewake',
    'Skin of Kabraxis',
    'Icetomb',
    'Elemental Disciple',
    'Scales of the Serpent',
    'Robe of Steel',
    'Silks of the Victor',
    'Khazra Pouch',
    'Lacuni Cowl',
    'Shiverhood',
    'Metalhead',
    "Aidan's Lament",
    'Eyes of Septumos',
    'Gromotvod',
    'Royal Circlet',
    'Crown of the Black Rose',
    "Trang-Oul's Breath",
    'Gaze of the Dead',
    'Witch Drum',
    'Lightforge',
    "Vaetia's Wall",
    'Shield of Hakan II',
    'Rainbow Fury',
    'Stone Guardian',
    'Sash of the Frozen Seas',
    'The Endless Loop',
    "Ashaera's Armor",
    "Nor Tiraj's Wisdom",
    "Lilith's Temptation",
    "Blackjade's Legacy",
    'Hellmouth',
    "Dacana's Fist",
    'Blind Anger',
    'Hammerfist',
    'Clockwork Slippers',
    "Titan's Steps",
    'Shrill Sacrament',
    'Binding Treads',
    "Rodeo's Tramplers",
    "Karcheus' Temptation",
    'Lionblood Crest',
    'Crown of Arnazeus',
    'Helepolis',
    'Vision of the Furies',
    'Impundulu',
    'Golden Chariot',
    'Silver Scorpion',
    'The Doom Gong of Xiansai',
    'Hexward',
    'Banner of Bitter Winds',
    'Shadowtwin',
    'Bear Grin',
    'Eagle Eye',
    "Bul Kathos' Temper",
    "Rodeo's Hide",
    "Toraja's Champion",
    'Coldhunger',
    'Savage Hunter',
    'Forest Defender',
    'Phoenix Beak',
    "Nature's Orphan",
    'Bottled Will-o-Wisp',
    'Dark Guardian',
    "Hero's Fang",
    'Grim Silhouette',
    "Barghest's Howl",
    'Hivemind',
    'The Book of Kalen',
    'Orationis Tenebris',
    "Argentek's Tide",
    "Astreon's Citadel",
    'Ignis Demonia',
    'The Ritualist',
    'Dervish of Aranoch',
    "Bartuc's Curse",
    'Zann Prodigy',
    'Armor of the Old Religion',
    'Maleficence'
]

SSU_ITEMS = [
    'The Eviscerator',
    'Sherazade',
    'Alnair',
    'Sarandeshi Hellcaller',
    'Astral Blade',
    'Eternal Vigil',
    "Azgar's Crystal",
    'Shadowfang',
    'Carsomyr',
    'The Grandfather',
    'Cold Blood',
    'Headsman',
    'The Colonel',
    'Dux Infernum',
    'Gotterdammerung',
    'Fire Hydra',
    'Hammer of Jholm',
    'Solar Scion',
    'The Redeemer',
    'Battlemaiden',
    'Vizjerei Fury',
    'Moonfang',
    'Heartseeker',
    'The Retiarius',
    'Stormchaser',
    'Freakshow',
    'Wizardspike',
    'Black Razor',
    'Drow Valor',
    'Dark Nemesis',
    'Piranha Swarm',
    'Penumbra',
    'Ophiophagus',
    "Deckard Cain's Heirloom",
    'Staff of Shadows',
    'Spire of Sarnakyle',
    'Absolute Zero',
    "Valthek's Command",
    'Etrayu',
    'Signal Fire',
    'Windforce',
    'Buriza-Do Kyanon',
    'Manticore Sting',
    "Athulua's Wrath",
    'Chasmstriker',
    "Panthera's Bite",
    "Titan's Revenge",
    'Sagittarius',
    'Mind Rake',
    'Black Ice',
    'Storm Blade',
    "Gladiator's Rage",
    'Berserrker',
    'The Pathless',
    'Colliding Fury',
    'Thunder King of Sescheron',
    'The King of Ents',
    'Eye of the Storm',
    'Mr. Painless',
    'The Biting Frost',
    'Soul Reaver',
    'Shadowfiend',
    'The Defiler',
    'Heart of Fire',
    'Advent of Hatred',
    'Stygian Fury',
    'Hand of Rathma',
    'Daydreamer',
    'Malevolence',
    'Smokeless Fire',
    'The Pyre',
    'Adjudicator',
    'The Angiris Star',
    'Malleus Maleficarum',
    'Venom Sting',
    "Jaguar's Grasp",
    'Holy Wars',
    'Mistress of Pain',
    'Glowing Vertigo',
    "Atanna's Key",
    "Galeona's Lash",
    'Steel Punisher',
    "Natalya's Deception",
    'The Petulant',
    'Scales of the Drake',
    'Flameskin',
    'Hide of the Basilisk',
    "Arkaine's Valor",
    'Wolverine Skin',
    'Segnitia',
    "Auriel's Robe",
    'Strength Beyond Strength',
    'Goetia Plate',
    'Khazra Plate',
    'Endless Pride',
    "Skull of the Viz-Jaq'taar",
    'Reapers',
    'Veil of Steel',
    'Undead Crown',
    'Dark Pact',
    'Soulsplitter',
    'Radiance',
    "Griffon's Eye",
    'Idol of Rygnar',
    'Black Masquerade',
    'The Flying Saucer',
    'Stormflyer',
    'Madawc Val Narian',
    'The Collector',
    'Celestial Barrier',
    'Lunar Eclipse',
    'Dementia',
    'Black Void',
    'Champion of the Triune',
    'Demonic Touch',
    'Rogue Foresight',
    'Facebreaker',
    'Lorekeeper',
    'Lamha Na Draoithe',
    'Spirit Walker',
    "Angel's Wrath",
    "Akarat's Trek",
    "Knight's Grace",
    "Rakkis' Benediction",
    'Rainbow Maiden',
    'Deviant Crown',
    'Asgardsreia',
    'Danmaku',
    'Crimson Dream',
    'Hammerfall',
    'Eternal Bodyguard',
    "Zayl's Temptation",
    'Warmonger',
    'Voice of Arreat',
    'Boarfrost',
    "Lilith's Legion",
    'Pawnstorm',
    "The Ancients' Legacy",
    "Greenwalker's Charge",
    'Sky Spirit',
    "Ranger's Disguise",
    'Homunculus',
    'Feardrinker',
    "The Sentinel's Sorrow",
    'Sinwar',
    'Blessed Wrath',
    'Veil of the Tainted Sun',
    'Mark of the Que-Hegan',
    'The Vanquisher',
    'The Last Crusader',
    'Herald of Zakarum',
    'Angelhost',
    'Cloak of the Outcast',
    'Adamantine Guard',
    'Frozen Heart',
    "Lachdanan's Visage",
    "Atanna Khan's Dress",
    'Despondence'
]

SSSU_ITEMS = [
    'Azurewrath',
    'Wintry Majesty',
    'The Point of No Return',
    'The Searing Heat',
    'The Worshipper',
    'Arrogance',
    'The Awakening',
    "Tyrael's Might",
    "Tinker's Gambit",
    'Unveiling Eye',
    'Desolation'
]

SETS = {
    "Achilios' Eagle Eye": "Achilios' Wake",
    "Achilios' Refuge": "Achilios' Wake",
    "Achilios' Sledgehammer": "Achilios' Wake",
    "Achilios' Stealth": "Achilios' Wake",
    'Ancient Bronze': 'Tundra Walker',
    'Angel of Death': "Astrogha's Moon",
    'Apefoot': 'Testament of the Apes',
    'Apehand': 'Testament of the Apes',
    'Apeshoot': 'Testament of the Apes',
    'Apeskin': 'Testament of the Apes',
    'Apeskull': 'Testament of the Apes',
    'Apprentice': "Oak's Teaching",
    'Eye of Wisdom (Druid)': "Oak's Teaching",
    'Archangel Dark Angel': 'Satanic Mantra',
    'Arctic Shard': 'Wintertide',
    'Eye of Wisdom (Sorceress)': 'Wintertide',
    'Avalanche': 'Mount Arreat',
    "Bear's Warding": 'Gathering of the Tribes',
    'Bilefroth Skin': 'Henchmen Trophies',
    "Blackskull's Horns": 'Henchmen Trophies',
    "Bremm's Retribution": 'Curse of the Zakarum',
    'Cauldron': 'The Mysteries',
    "Celestia's Charge": "Celestia's Myth",
    "Celestia's Passion": "Celestia's Myth",
    "Celestia's Ribbon": "Celestia's Myth",
    "Celestia's Wings": "Celestia's Myth",
    'Charged Cloud': 'Thunderstorm',
    'Eye of Wisdom (Amazon)': 'Thunderstorm',
    "Cinadide's Anvil": "Cinadide's Craft",
    "Cinadide's Bellows": "Cinadide's Craft",
    "Cinadide's Bender": "Cinadide's Craft",
    "Cinadide's Malus": "Cinadide's Craft",
    'Darkling': "Astrogha's Moon",
    'Dead Lens': 'Universal Law',
    'Death Magnet': 'Battle Devices',
    'Eye of Wisdom (Assassin)': 'Battle Devices',
    'Destiny': 'Spirits of the Nephalem',
    'Doomcloud Spine': 'Henchmen Trophies',
    'Dyad': "Adria's Circle",
    'Earth': 'Pantheon',
    'Elemental Clash': 'Elemental Children',
    'Elemental Fury': 'Elemental Children',
    'Elemental Spirit': 'Elemental Children',
    'Elemental Storm': 'Elemental Children',
    'Emerald Cloud': 'Rainbow Warrior',
    'Emerald Earth': 'Rainbow Warrior',
    'Emerald Flower': 'Rainbow Warrior',
    'Emerald Sky': 'Rainbow Warrior',
    'Eruption': 'Mount Arreat',
    'Fangskin Scales': 'Henchmen Trophies',
    'Femur of the Prophet': 'Celestial Orchard',
    'Fire': 'Pantheon',
    'Frost': 'Pantheon',
    "Geleb's Greed": 'Curse of the Zakarum',
    "Giyua's Sacrum": 'Celestial Orchard',
    'Grey Ranger': 'Tundra Walker',
    "Hadriel's Avenger": "Hadriel's Lore",
    "Hadriel's Presence": "Hadriel's Lore",
    "Hadriel's Pure Heart": "Hadriel's Lore",
    "Hadriel's Wings": "Hadriel's Lore",
    'Hand of Inarius': 'Sanctuary',
    "Hunter's Camouflage": 'Big Game Hunter',
    "Hunter's Claw Fist": 'Big Game Hunter',
    "Hunter's Skin": 'Big Game Hunter',
    "Hunter's Trackless Step": 'Big Game Hunter',
    'Hypersurface': 'Universal Law',
    'Idol of Fortune': 'Trophy Hunter',
    'Imperial Guard': 'Guardian of the Sightless Eye',
    'Eye of Wisdom (Barbarian)': 'Guardian of the Sightless Eye',
    "Imperius' Aura": "Imperius' Edict",
    "Imperius' Radiance": "Imperius' Edict",
    "Imperius' Sky Hammer": "Imperius' Edict",
    "Imperius' Winged Feet": "Imperius' Edict",
    'Killing Vector': 'Universal Law',
    "Lazarus' Chasuble": 'Archbishop Lazarus',
    "Lazarus' Lamen": 'Archbishop Lazarus',
    "Lazarus' Surplice Cap": 'Archbishop Lazarus',
    "Lazarus' Votive Lamp": 'Archbishop Lazarus',
    'Lend Me Thy Light': 'Satanic Mantra',
    "Lilith's Disguise": 'Sanctuary',
    "Lone Wolf's Claws": "Lone Wolf's Path",
    "Lone Wolf's Fur": "Lone Wolf's Path",
    "Lone Wolf's Maul": "Lone Wolf's Path",
    "Lone Wolf's Track": "Lone Wolf's Path",
    "Maffer's Frenzy": 'Curse of the Zakarum',
    "Malthael's Crown": "Malthael's Sanctuary",
    "Malthael's Halo": "Malthael's Sanctuary",
    "Malthael's Ward": "Malthael's Sanctuary",
    "Malthael's Wrath": "Malthael's Sanctuary",
    "Marchosias' Anger": "Marchosias' Essence",
    "Marchosias' Evil Grin": "Marchosias' Essence",
    "Marchosias' Hatred": "Marchosias' Essence",
    "Marchosias' Might": "Marchosias' Essence",
    'Monad': "Adria's Circle",
    "Nature's Embrace": 'Caoi Dulra',
    "Nature's Vigil": 'Caoi Dulra',
    "Nature's Will": 'Caoi Dulra',
    "Nature's Wrath": 'Caoi Dulra',
    'Pentacle': 'The Mysteries',
    'Quantum Bevel': 'Universal Law',
    "Rathma's Chase": "Rathma's Empire",
    "Rathma's Death Gaze": "Rathma's Empire",
    "Rathma's Skeleton": "Rathma's Empire",
    "Rathma's Tyranny": "Rathma's Empire",
    'Ravine': 'Mount Arreat',
    "Red Vex' Curse": "Red Vex' Embrace",
    "Red Vex' Flayer": "Red Vex' Embrace",
    "Red Vex' Idol": "Red Vex' Embrace",
    "Red Vex' Sin": "Red Vex' Embrace",
    'Sacred Charge': 'Spirits of the Nephalem',
    'Sacred Circle': 'The Mysteries',
    'Sacrificial Mind': 'The Offering',
    'Eye of Wisdom (Necromancer)': 'The Offering',
    "Scosglen's History": 'Last King of Scosglen',
    "Scosglen's Legends": 'Last King of Scosglen',
    "Scosglen's Myths": 'Last King of Scosglen',
    "Scosglen's Tales": 'Last King of Scosglen',
    "Serpent's Coil": 'The Snake Pit',
    "Serpent's Fangs": 'The Snake Pit',
    "Serpent's Tail": 'The Snake Pit',
    "Serpent's Tongue": 'The Snake Pit',
    "Snake's Battle Chant": 'Gathering of the Tribes',
    'Snowstorm': 'Mount Arreat',
    "Stareye's Claws": 'Henchmen Trophies',
    'Steppe Sleeper': 'Tundra Walker',
    'Tetrad': "Adria's Circle",
    'The Catalyst': 'Vizjerei Dominion',
    'The Coming Storm': 'Gathering of the Tribes',
    'The Conqueror': 'Trophy Hunter',
    'The Darkness': 'Vizjerei Dominion',
    'The Dragon Grave': 'Celestial Orchard',
    'The Guardian': 'Spirits of the Nephalem',
    'The Hunger': 'Vizjerei Dominion',
    'The Judgment': 'Vizjerei Dominion',
    'The Presence': 'Vizjerei Dominion',
    'The Protector': 'Spirits of the Nephalem',
    'The Trickster': 'Celestial Orchard',
    'The Witness': 'Armageddon',
    'Eye of Wisdom (Paladin)': 'Armageddon',
    "Through Death's Veil": 'Satanic Mantra',
    'Till We Have Heaven In Sight': 'Satanic Mantra',
    'Tower Defense': 'The Towerlord',
    'Tower Denial': 'The Towerlord',
    'Tower Rush': 'The Towerlord',
    'Tower Wall': 'The Towerlord',
    "Tracker's Effigy": 'Creed',
    "Tracker's Runeward": 'Creed',
    "Tracker's Stealth": 'Creed',
    "Tracker's Strike": 'Creed',
    'Triad': "Adria's Circle",
    'Vale Hunter': 'Tundra Walker',
    "Vasily's Crescent": "Vasily's Following",
    "Vasily's Eclipse": "Vasily's Following",
    "Vasily's Falling Star": "Vasily's Following",
    "Vasily's Shepherd Moon": "Vasily's Following",
    'Viper Skin': "Astrogha's Moon",
    "Vizjun's Engine": "Vizjun's Devices",
    "Vizjun's Foresight": "Vizjun's Devices",
    "Vizjun's Monitor": "Vizjun's Devices",
    "Vizjun's Science": "Vizjun's Devices",
    "Warmage's Breath": 'The Warmage',
    "Warmage's Fireblade": 'The Warmage',
    "Warmage's Flameshroud": 'The Warmage',
    "Warmage's Wake": 'The Warmage',
    'Water': 'Pantheon',
    'Witchblade': 'The Mysteries',
    "Witchhunter's Crucifix": "Witchhunter's Attire",
    "Witchhunter's Faith": "Witchhunter's Attire",
    "Witchhunter's Ire": "Witchhunter's Attire",
    "Witchhunter's Hood": "Witchhunter's Attire",
    "Wolf's Fang": 'Gathering of the Tribes',
    'Worldstone': 'Sanctuary',
    "Wyand's Perfidy": 'Curse of the Zakarum',
    "Yaerius' Alembic": "Yaerius' Grey Omen",
    "Yaerius' Mediation": "Yaerius' Grey Omen",
    "Yaerius' Simulacrum": "Yaerius' Grey Omen",
    "Yaerius' Untruth": "Yaerius' Grey Omen",
    "Zann Esu's Binding Circle": "Zann Esu's Secrets",
    "Zann Esu's Charm": "Zann Esu's Secrets",
    "Zann Esu's Robes": "Zann Esu's Secrets",
    "Zann Esu's Rune Loop": "Zann Esu's Secrets",
    "Zerae's Holy Wrath": "Zerae's Divinity",
    "Zerae's Redemption": "Zerae's Divinity",
    "Zerae's Refinement": "Zerae's Divinity",
    "Zerae's Vindication": "Zerae's Divinity"
}

RINGS = [
    'Der Nebelring',
    'Ras Algethi',
    'Sigil of Tur Dulra',
    'Seal of the Nephalem Kings',
    'Ouroboros',
    'Witchcraft',
    "Giant's Knuckle",
    'Empyrean Glory',
    'Bad Mood',
    'Elemental Band',
    'Adrenaline Rush',
    'Black Hand Sigil',
    'Signet of the Gladiator',
    'Ring of Truth',
    'Ring of Disengagement',
    'Ring of Regha',
    'Earth Rouser',
    "Xorine's Ring",
    'Ripstar',
    'The Seal of Kharos',
    'Empyrean Band',
    'Bloodbond',
    "Myokai's Path",
    'Sigil of the 7 Deadly Sins',
    "Assur's Bane"
]

AMULETS = [
    'Black Dwarf',
    'Klaatu Barada Nikto',
    "Vizjerei's Necklace",
    'Locket of Dreams',
    'The Tesseract',
    'Niradyahk',
    'Death Ward',
    'Dyers Eve',
    "Quov Tsin's Talisman",
    'Gallowlaugh',
    'Beads of the Snake Queen',
    'Lamen of the Archbishop',
    'In For The Kill',
    'Khanduran Royal Pendant',
    'The Buried Hawk',
    'Scarab of Death',
    'Fren Slairea',
    'Hangman',
    'Angel Heart',
    'The Dreamcatcher',
    "Athulua's Oracle",
    'Felblood',
    'Teganze Pendant',
    'Witchmoon',
    "Jerhyn's Tawiz",
    'Celestial Sigil'
]

JEWELS = [
    'Heavenstone',
    'Xepera Xeper Xeperu',
    "Zann Esu's Stone",
    'Suicide Note',
    "Inarius' Rock",
    'Arkenstone',
    'Atomus',
    'Jewel of Luck',
    'Storm Shard',
    'The Boulder',
    'Demonstone Blood',
    "Asheara's Cateye",
    'Farsight Globe',
    'Zakarum Stoning Rock',
    'Katamari',
    'Wishmaster'
]

QUIVERS = [
    'Bag of Tricks',
    "Kingsport's Signals",
    'Locust Hive',
    'Cindercone',
    'Hanabigami',
    'Lammergeier',
    "Devil's Dance",
    'Plague Gland',
    "Larzuk's Bandolier",
    'The Tranquilizer'
]

MOS = [
    'Larzuk\'s Round Shot',
    'Vizjun\'s Ball Bearing',
    'Nor Tiraj\'s Flaming Sphere',
    'The Demon Core',
    'Uldyssian\'s Spirit',
    'Orb of Annihilation',
    'Warbringer',
    'Ten Pin Striker',
    'Wrathspirit',
    'Idol of Stars',
    'Nagapearl',
    'The Moon Crystal',
    'Auriel\'s Focus',
    'Solitude',
    'Crystal of Tears',
    'Essence of Itherael',
    'Periapt of Life',
    'Lodestone',
    'Kara\'s Trinket',
    'Monsterball',
    'Heart of Frost',
    'Relic of Yaerius',
    'The Endless Light',
    'Explorer\'s Globe',
    'The Perfect Sphere',
    'Marksman\'s Eye',
    'Zayl\'s Soul Orb',
    'Farnham\'s Lost Marble',
    'Eye of Malic',
    'Apple of Discord',
    'Elemental Ire',
    'Empyrean Touch',
    'Path of Brutality',
    'Celestial Wind',
    'Elemental Dominion',
    'Sigil of Absolution',
    'Breath of Thaumaturgy',
    'Arcane Hunger'
]

CHARMS = [
    'Sunstone of the Twin Seas',
    'Sacred Sunstone',
    'Shadow Vortex',
    'Worldstone Orb',
    'Caoi Dulra Fruit',
    'Soulstone Shard',
    'Eye of Divinity',
    'Nexus Crystal',
    'The Butcher\'s Tooth',
    'Optical Detector',
    'Laser Focus Crystal',
    'Sacred Worldstone Key',
    'Scroll of Kings',
    'Visions of Akarat',
    'Moon of the Spider',
    'Horazon\'s Focus',
    'The Black Road',
    'Legacy of Blood',
    'Fool\'s Gold',
    'Spirit Trance Herb',
    'Idol of Vanity',
    'Azmodan\'s Heart',
    'Weather Control',
    'Silver Seal of Ureh',
    'Crystalline Flame Medallion',
    'Soul of Kabraxis',
    'Eternal Bone Pile',
    'The Book of Lies',
    'Dragon Claw',
    'The Ancient Repositories',
    'Xazax\'s Illusion',
    'Astrogha\'s Venom Stinger',
    'The Sleep',
    'Neutrality Pact',
    'Glorious Book of Median',
    'Rathma\'s Supremacy',
    'Vial of Elder Blood',
    'Six Angel Bag',
    'Hammer of the Taan Judges',
    'Zakarum\'s Ear',
    'Sunstone of the Gods',
    'Umbaru Treasure',
    'Corrupted Wormhole',
    'Demonsbane',
    'Lylia\'s Curse',
    'Cold Fusion Schematics',
    'Spirit of Creation'
]

TROPHIES = [
    'Archbishop Lazarus Trophy',
    'Astrogha Trophy',
    'Banisher of Light Trophy',
    'Duncraig Trophy',
    'Eve of Destruction Trophy',
    'Ghosts of Old Bremmtown Trophy',
    'Heart of Sin Trophy',
    'Judgement Day Trophy',
    'Kingdom of Shadow Trophy',
    'Legacy of Blood Trophy',
    'Lord of Lies Trophy',
    "Nephalem's Sacrifice Trophy",
    'Quov Tsin Trophy',
    'The Triune Trophy',
    'The Veiled Prophet Trophy',
    'The Void Trophy',
    'Tran Athulua Trophy',
    'Viz-jun Trophy',
    'Xazax Trophy',
    'Yshari Sanctum Trophy',
    'Archbishop Lazarus Fragment',
    'Astrogha Fragment',
    'Banisher of Light Fragment',
    'Duncraig Fragment',
    'Eve of Destruction Fragment',
    'Ghosts of Old Bremmtown Fragment',
    'Heart of Sin Fragment',
    'Judgement Day Fragment',
    'Kingdom of Shadow Fragment',
    'Legacy of Blood Fragment',
    'Lord of Lies Fragment',
    "Nephalem's Sacrifice Fragment",
    'Quov Tsin Fragment',
    'The Triune Fragment',
    'The Veiled Prophet Fragment',
    'The Void Fragment',
    'Tran Athulua Fragment',
    'Viz-jun Fragment',
    'Xazax Fragment',
    'Yshari Sanctum Fragment'
]

SHRINE_VESSELS = [
    'Creepy Vessel',
    'Sacred Vessel',
    'Quiet Vessel',
    'Hidden Vessel',
    'Tainted Vessel',
    'Ornate Vessel',
    'Fascinating Vessel',
    'Intimidating Vessel',
    'Weird Vessel',
    'Trinity Vessel',
    'Spiritual Vessel',
    'Eerie Vessel',
    'Enchanted Vessel',
    'Shimmering Vessel',
    'Magical Vessel',
    'Abandoned Vessel'
]

SHRINES = [
    'Creepy Shrine',
    'Sacred Shrine',
    'Quiet Shrine',
    'Hidden Shrine',
    'Tainted Shrine',
    'Ornate Shrine',
    'Fascinating Shrine',
    'Intimidating Shrine',
    'Weird Shrine',
    'Trinity Shrine',
    'Spiritual Shrine',
    'Eerie Shrine',
    'Enchanted Shrine',
    'Shimmering Shrine',
    'Magical Shrine',
    'Abandoned Shrine'
]

VESSEL_TO_SHRINE = {
    'Creepy Vessel': 'Creepy Shrine',
    'Sacred Vessel': 'Sacred Shrine',
    'Quiet Vessel': 'Quiet Shrine',
    'Hidden Vessel': 'Hidden Shrine',
    'Tainted Vessel': 'Tainted Shrine',
    'Ornate Vessel': 'Ornate Shrine',
    'Fascinating Vessel': 'Fascinating Shrine',
    'Intimidating Vessel': 'Intimidating Shrine',
    'Weird Vessel': 'Weird Shrine',
    'Trinity Vessel': 'Trinity Shrine',
    'Spiritual Vessel': 'Spiritual Shrine',
    'Eerie Vessel': 'Eerie Shrine',
    'Enchanted Vessel': 'Enchanted Shrine',
    'Shimmering Vessel': 'Shimmering Shrine',
    'Magical Vessel': 'Magical Shrine',
    'Abandoned Vessel': 'Abandoned Shrine'
}

IGNORED_ITEMS = [
    'Apple',
    'Horadric Cube',
    'Minor Healing Potion',
    'Light Healing Potion',
    'Healing Potion',
    'Greater Healing Potion',
    'Super Healing Potion',
    'Minor Mana Potion',
    'Light Mana Potion',
    'Mana Potion',
    'Greater Mana Potion',
    'Super Mana Potion',
    'Rejuvenation Potion',
    'Full Rejuvenation Potion',
    'Ring',
    'Amulet',
    'Catalyst of Disenchantment',
    'Catalyst of Learning',
    'Signet of Gold',
    'Greater Signet of Gold',
    'Large Axe (1)',
    'Quilted Armor (1)',
    'Buckler (1)',
    'Hand Axe (1)',
    'Javelin (1)',
    'Katar (1)',
    'Short Staff (1)',
    'Short Sword (1)',
    'Wand (1)'
]

RUNEWORDS = [
  'Dawn',
  'Shark',
  'Enyo',
  'Azrael',
  'Void',
  'Oblivion',
  'Berith',
  'Gehenna',
  'Triune',
  'Adramelech',
  'Archangel',
  'Shattered Stone',
  'Banshee',
  'Amok',
  'Shockwave',
  'Hornet',
  'Balance',
  'Nyx',
  'Hive',
  'Phantom',
  'Curse',
  'Typhaon',
  'Stardust',
  'Dead Man\'s Breath',
  'Thammuz',
  'Python',
  'Cyclops',
  'Tynged',
  'Tartarus',
  'Araboth',
  'Tombstone',
  'Faseroptic',
  'Urada',
  'Minefield',
  'Instinct',
  'Sabertooth',
  'Midas\' Touch',
  'Myrmidon',
  'Asymptomatic',
  'Endor',
  'Atlacamani',
  'Seed of Conflict',
  'Solarion',
  'King\'s Blood',
  'Rattus',
  'Malicicle',
  'Demhe',
  'Arachnophilia',
  'Calypso',
  'Neurogenesis',
  'Pax Mystica',
  'Hadad',
  'Summanus',
  'Akhenaten',
  'Ljosalf',
  'Aes Dana',
  'Elverfolk',
  'Erilaz',
  'Zodiac',
  'Kyrie',
  'Hand of Frost',
  'Prophecy',
  'Bane',
  'Judas',
  'Path',
  'Jokulmorder',
  'Gabriel',
  'Durga',
  'Galdr',
  'Apostasy',
  'Oris\' Herald',
  'Raid',
  'Hastata',
  'Haste',
  'Hastilude',
  'Hastur',
  'Hastin',
  'Fleshbane',
  'Patriot',
  'Chrysopelea',
  'Dajjal',
  'Quantum',
  'Myriad',
  'Naiad',
  'Burlesque',
  'Tau',
  'Dead Star',
  'Cheetah',
  'Fennec',
  'Manitou',
  'Raptor',
  'Thundercloud',
  'Kodiak',
  'Dragon Seed',
  'Aspect',
  'Corsair',
  'Ice Breaker',
  'Eris',
  'Colliding Worlds',
  'Manta',
  'Cecaelia',
  'Arnazeus Pinnacle',
  'Aegina',
  'Titanomachia',
  'Sankara',
  'Rusalka',
  'Evanescence',
  'Freybug',
  'Flame',
  'Scar',
  'Firefly',
  'Trishula',
  'Herfjotur',
  'Stalactite',
  'Specter',
  'Askari Device',
  'Shedim',
  'Carabosse',
  'Fiend',
  'Riot',
  'Judge',
  'Choronzon',
  'Anarchy',
  'Hail',
  'Nahemah',
  'Joker',
  'Perfection',
  'Khattak',
  'Shamo',
  'Hieros Gamos',
  'Lataif-as-Sitta',
  'Oniwaka',
  'Blooddancer',
  'Ram',
  'Essus',
  'Thunderbird',
  'Gharaniq',
  'Savitr',
  'Skarn',
  'Anak',
  'Khan',
  'Lahmu',
  'Kahless',
  'Gilgamesh',
  'El\'druin',
  'Wolfsangel',
  'Soldier of Light',
  'Peacock',
  'Lynx',
  'Sylvanshine',
  'Tarqeq',
  'Cernunnos',
  'Raudna',
  'Dirge',
  'Amphibian',
  'Ocean',
  'Samhain',
  'Augur',
  'Lincos',
  'Laadan',
  'Lojban',
  'Loxian',
  'Hermanubis',
  'Fiacla-Gear\'s Weathervane',
  'Black Cat',
  'Mantra',
  'Lemuria',
  'Chthon',
  'Eventide',
  'Inti',
  'Leviathan',
  'Tzeentch',
  'Bartuc\'s Eye',
  'Loa',
  'Jinx',
  'Misery',
  'Seid',
  'Roc',
  'Mkodos',
  'Cut',
  'Deep Water',
  'Eurynome',
  'Ladon',
  'Hali',
  'Dagda',
  'Santa Compana',
  'Styx',
  'Xazax',
  'Koan',
  'Ghoul',
  'Dead Ringer',
  'Ngozi',
  'Semhazai',
  'Krypteia',
  'Doomguard',
  'Genie',
  'Atlantis',
  'Aether',
  'Crucible',
  'Kronos',
  'Rhea',
  'Force of Mind',
  'Ensi',
  'Nehushtan',
  'Resheph',
  'Taqiyya',
  'Orisha',
  'Rex Deus',
  'Jaguar',
  'Hadriel\'s Protector',
  'Jihad',
  'Intifada',
  'Lammasu',
  'Quaoar',
  'Takfir',
  'Brahman',
  'Oriflamme',
  'Skilt en Vriend',
  'Judgement',
  'Circe',
  'Ker',
  'Vertigo',
  'Gravastar',
  'Kabbalah',
  'Hestia',
  'Kallisti',
  'Sauron',
  'Helgrotha',
  'Inanna',
  'Brocken',
  'Grace',
  'Khany',
  'Shaula',
  'Sway of the Stars',
  'Dark Exile',
  'Rebel',
  'Lumen Arcana',
  'Paaliaq',
  'Victory\n(Median XL - 6 years)',
  'Thelema',
  'Cathedral',
  'Mirage',
  'Dragonheart',
  'Erawan',
  'Unity',
  'Linga Sharira',
  'Pygmalion',
  'Eternal\nMedian 2005-2012\nThanks everyone!',
  'Hellfire Plate',
  'Summit',
  'Cannonball',
  'Ra',
  'Alchemy',
  'Dreadlord',
  'Bogspitter',
  'Eidolon',
  'Amanita',
  'Thundercap',
  'Checkmate',
  'Sphinx',
  'Lily',
  'Eulenspiegel',
  'Wintermute',
  'Indigo',
  'Rathma\'s Blessing',
  'Geas',
  'Pharaoh',
  'Nomad',
  'Goddess',
  'Kodo',
  'Wall of Fire',
  'Avatar',
  'Derweze',
  'Khalim\'s Protector',
  'Rainbow',
  'Prodigy',
  'Fuse',
  'Pulsa Dinura',
  'Truce',
  'Dyaus Pita',
  'Ahriman',
  'Nero',
  'Lysra',
  'Iblis',
  'Mercy',
  'Brawl',
  'Kali',
  'Aiwass',
  'Skald',
  'Icarus',
  'Drekavac',
  'Snowsquall',
  'Retribution',
  'Knave',
  'Epicenter',
  'Outlaw',
  'Ginfaxi',
  'Craton',
  'Megalith',
  'Nephilim',
  'Hibagon',
  'Riptide',
  'Wind Runner',
  'Stata Mater',
  'Bona Dea',
  'Amaterasu',
  'Siegfried',
  'Cambion',
  'Lohengrin',
  'Unicorn',
  'Shaheeda',
  'Eaglehorn Mask',
  'Edda',
  'Lion',
  'Eloi',
  'Nix',
  'Ea',
  'Eos',
  'Heart of Skovos',
  'Afrit',
  'Rahab',
  'Iambe',
  'Ligeia',
  'Dar-Al-Harb',
  'Scorched Earth',
  'Orchid',
  'Shadowsteps',
  'Algiz',
  'Nasrudin',
  'Ekam',
  'Fawkes',
  'Sagarmatha',
  'Morthwyrtha',
  'Wodziwob',
  'Greisen',
  'Force Shock',
  'Enmerkar',
  'Warpath',
  'Gauntlet',
  'Huracan',
  'E-Engur-A',
  'Tonatiuh',
  'Triune\'s Blessing',
  'Aegipan',
  'Nezha',
  'Natha',
  'Norma',
  'Grove',
  'Slyph',
  'Nigra',
  'Nature\'s Grace',
  'Cube',
  'Warlock',
  'Nahual',
  'Lorelei',
  'Quimbanda',
  'Wyrm',
  'Hecatomb',
  'Twisted Mind',
  'Ilmatar',
  'Hierodule',
  'Crusade',
  'Surya',
  'Malakbel',
  'Rotundjere',
  'Battle Rage',
  'Asmodai',
  'Sangreal',
  'Zohar',
  'Asclepion',
  'Amaymon',
  'Myrrhbearer',
  'Lightwell',
  'Lyrannikin',
  'Kundalini',
  'Demeter',
  'Curandera',
  'Astarte',
  'Oracle',
  'Vanity',
  'Comaetho',
  'Venefica',
  'Cassilda',
  'Space Dementia',
  'Dawn',
  'Shark',
  'Enyo',
  'Azrael',
  'Void',
  'Banshee',
  'Amok',
  'Shockwave',
  'Hornet',
  'Balance',
  'Nyx',
  'Hive',
  'Thammuz',
  'Python',
  'Cyclops',
  'Instinct',
  'Myrmidon',
  'Endor',
  'King\'s Blood',
  'Demhe',
  'Pax Mystica',
  'Hadad',
  'Summanus',
  'Akhenaten',
  'Ljosalf',
  'Prophecy',
  'Bane',
  'Judas',
  'Path',
  'Raid',
  'Hastata',
  'Haste',
  'Patriot',
  'Chrysopelea',
  'Dajjal',
  'Quantum',
  'Cheetah',
  'Fennec',
  'Manitou',
  'Aspect',
  'Corsair',
  'Ice Breaker',
  'Aegina',
  'Titanomachia',
  'Scar',
  'Firefly',
  'Shedim',
  'Carabosse',
  'Fiend',
  'Riot',
  'Judge',
  'Khattak',
  'Shamo',
  'Ram',
  'Essus',
  'Thunderbird',
  'Gharaniq',
  'Peacock',
  'Lynx',
  'Sylvanshine',
  'Ocean',
  'Samhain',
  'Augur',
  'Lincos',
  'Black Cat',
  'Mantra',
  'Lemuria',
  'Chthon',
  'Loa',
  'Jinx',
  'Misery',
  'Deep Water',
  'Eurynome',
  'Ladon',
  'Koan',
  'Ghoul',
  'Genie',
  'Atlantis',
  'Aether',
  'Ensi',
  'Nehushtan',
  'Resheph',
  'Jihad',
  'Intifada',
  'Lammasu',
  'Quaoar',
  'Circe',
  'Ker',
  'Vertigo',
  'Gravastar',
  'Inanna',
  'Brocken',
  'Rebel',
  'Lumen Arcana',
  'Paaliaq',
  'Victory\n(Median XL - 6 years)',
  'Thelema',
  'Cathedral',
  'Mirage',
  'Natasha\'s Legacy',
  'Summit',
  'Cannonball',
  'Ra',
  'Alchemy',
  'Sphinx',
  'Lily',
  'Geas',
  'Pharaoh',
  'Nomad',
  'Goddess',
  'Rainbow',
  'Prodigy',
  'Fuse',
  'Iblis',
  'Mercy',
  'Brawl',
  'Kali',
  'Aiwass',
  'Epicenter',
  'Outlaw',
  'Ginfaxi',
  'Craton',
  'Stata Mater',
  'Bona Dea',
  'Amaterasu',
  'Siegfried',
  'Edda',
  'Afrit',
  'Rahab',
  'Iambe',
  'Ligeia',
  'Algiz',
  'Nasrudin',
  'Ekam',
  'Fawkes',
  'Enmerkar',
  'Warpath',
  'Aegipan',
  'Nezha',
  'Natha',
  'Cube',
  'Warlock',
  'Ilmatar',
  'Hierodule',
  'Asmodai',
  'Sangreal',
  'Zohar',
  'Lyrannikin',
  'Kundalini',
  'Demeter',
  'Curandera'
]

MISC_ITEMS = [
    'Belladonna Extract',
    'Small Cycle',
    'Medium Cycle',
    'Large Cycle',
    'Sunless Crystal Bird',
    'Deity\'s Bow',
    'Mystic Dye',
    'Dark Summoning',
    'Ancient Book',
    'Emblem of Destruction',
    'Emblem of Hatred',
    'Emblem of Lies',
    'Emblem of Pain',
    'Emblem of Suffering',
    'Emblem of Terror',
    'Oil of Conjuration',
    'Oil of Enhancement',
    'Oil of Craft',
    'Oil of Renewal',
    'Oil of Luck',
    'Oil of Disjunction',
    'Mephisto\'s Soulstone',
    'Dream Fragment (1)',
    'Dream Fragment (2)',
    'Dream Fragment (3)',
    'Dream Fragment (4)',
    'Dream Fragment (5)',
    'Star Chart (1)',
    'Star Chart (2)',
    'Star Chart (3)',
    'Star Chart (4)',
    'Key',
    'Mark of Infusion',
    'Mystic Orb'
]

DEFAULT_TRADE_POST_TEMPLATE = '''[color=#FFFF00][size=26]Selling[/size][/color]
[hr][/hr]
[color=#00FF00][size=24]Sets[/size][/color]
[hr][/hr]
{sets}

[color=#804000][size=24]SU[/size][/color]
[hr][/hr]
{su}

[color=#804000][size=24]SSU[/size][/color]
[hr][/hr]
{ssu}

[color=#804000][size=24]SSSU[/size][/color]
[hr][/hr]
{sssu}

[color=#808080][size=24]Runewords[/size][/color]
[hr][/hr]
{rws}

[color=#CD853F][size=24]Crafted[/size][/color]
[hr][/hr]
{crafted}

[color=#804000][size=24]Rings/Amulets/Quivers/MOs/Jewels[/size][/color]
[hr][/hr]
{rings}

{amulets}

{quivers}

{mos}

{jewels}

[color=#808080][size=24]Bases[/size][/color]
[hr][/hr]
{rw_bases}

{shrine_bases}

[color=#FF7F50][size=24]Charms[/size][/color]
[hr][/hr]
{charms}

[color=#FFA500][size=24]Trophies[/size][/color]
[hr][/hr]
{trophies}

[color=#FFFFFF][size=24]Misc[/size][/color]
[hr][/hr]
{shrines}

{misc}
'''
