SU_ITEMS = [
    'Screen of Viz-Jaq\'Taar',
    'Razorspine',
    'Hratli\'s Craft',
    'Alchemist Apron',
    'Hepsheeba\'s Mantle',
    'Candlewake',
    'Skin of Kabraxis',
    'Icetomb',
    'Elemental Disciple',
    'Scales of the Serpent',
    'Robe of Steel',
    'Silks of the Victor',
    'Lacuni Cowl',
    'Shiverhood',
    'Metalhead',
    'Aidan\'s Lament',
    'Eyes of Septumos',
    'Gromotvod',
    'Royal Circlet',
    'Crown of the Black Rose',
    'Trang-Oul\'s Breath',
    'Gaze of the Dead',
    'Witch Drum',
    'Lightforge',
    'Shield of Hakan II',
    'Rainbow Fury',
    'Stone Guardian',
    'The Endless Loop',
    'Ashaera\'s Armor',
    'Nor Tiraj\'s Wisdom',
    'Lilith\'s Temptation',
    'Blackjade\'s Legacy',
    'Hammerfist',
    'Dacana\'s Fist',
    'Blind Anger',
    'Hellmouth',
    'Titan\'s Steps',
    'Shrill Sacrament',
    'Binding Treads',
    'Rodeo\'s Tramplers',
    'Karcheus\' Temptation',
    'Lionblood Crest',
    'Crown of Arnazeus',
    'Helepolis',
    'Vision of the Furies',
    'Impundulu',
    'Golden Chariot',
    'Silver Scorpion',
    'The Doom Gong of Xiansai',
    'Hexward',
    'Banner of Bitter Winds',
    'Rodeo\'s Hide',
    'Toraja\'s Champion',
    'Shadowtwin',
    'Bear Grin',
    'Eagle Eye',
    'Bul Kathos\' Temper',
    'Coldhunger',
    'Savage Hunter',
    'Forest Defender',
    'Phoenix Beak',
    'Nature\'s Orphan',
    'Bottled Will-o-Wisp',
    'Dark Guardian',
    'Hero\'s Fang',
    'Grim Silhouette',
    'Barghest\'s Howl',
    'Hivemind',
    'The Book of Kalen',
    'Orationis Tenebris',
    'Argentek\'s Tide',
    'Astreon\'s Citadel',
    'Ignis Demonia',
    'The Ritualist',
    'Dervish of Aranoch',
    'Bartuc\'s Curse',
    'Zann Prodigy',
    'Armor of the Old Religion',
    'The Xiphos',
    'Kraken\'s Cutlass',
    'Saber of the Stormsail',
    'Aeterna',
    'Aurumvorax',
    'Shadowsabre',
    'Qarak\'s Will',
    'Tylwulf\'s Betrayal',
    'Blacktongue',
    'Feltongue',
    'Grotesque Bite',
    'The Captain',
    'Nimmenjuushin',
    'Elder Law',
    'Dreamflange',
    'Firequeen',
    'Viper Mandate',
    'Legion',
    'Dead Lake\'s Lady',
    'Thunderbane',
    'Screaming Serpent',
    'Night\'s Embrace',
    'Lancea',
    'Steel Pillar',
    'Darkspite',
    'The Pride of Caldeum',
    'Bitter Harvest',
    'Bone Scalpel',
    'Frostneedle',
    'Plunderbird',
    'Meshif\'s Iron Parrot',
    'Warshrike',
    'Buzzbomb',
    'Lacerator',
    'Griefbringer',
    'Vizjerei\'s Folly',
    'Shamanka',
    'Aerin Nexus',
    'Xorine\'s Cane',
    'Spire of Kehjan',
    'Chillstring',
    'Gjallarhorn',
    'Fleshstinger',
    'Hellreach',
    'Ratbane',
    'Nihlathak\'s Bombard',
    'Horned Hunter',
    'Askarbydd',
    'Serenthia\'s Scorn',
    'Hellrain',
    'Twin Terrors',
    'Dreamweaver',
    'Legio Di Manes',
    'Frysturgard',
    'Kaskara of the Taan',
    'Talic the Unwilling',
    'The Pathless',
    'Esubane',
    'Skeld\'s Battlesong',
    'Cleaver of Mirrors',
    'Peace Warder',
    'Ord Rekar\'s Testament',
    'Yaggai\'s Sagaris',
    'Faerie Pyre',
    'Azgar\'s Mark',
    'Guardian of Scosglen',
    #'Hanfod Tân', Wrong encoding aahz :kek:
    'Reaper\'s Hand',
    'Karybdus\' Descent',
    'Dreamflayer',
    'Mente Scura',
    'Hwanin\'s Hwacha',
    'Nymyr\'s Shadow',
    'Manastorm',
    'Storm Focus',
    'The Pyre',
    'Darkfeast',
    'Herald of Pestilence',
    'Chober Chaber',
    'In Fero Salva',
    'Black Sun Spear',
    'Habacalva\'s Legacy',
    'Ghostmoon',
    'Bane of the Horadrim',
    'Gravetalon',
    'Leah\'s Vision',
    'Starhawk',
    'Maleficence',
    'Grim Visor',
    'Iron Shard',
    'King\'s Desire'
]

SSU_ITEMS = [
    'Natalya\'s Deception',
    'The Petulant',
    'Scales of the Drake',
    'Hide of the Basilisk',
    'Arkaine\'s Valor',
    'Wolverine Skin',
    'Segnitia',
    'Auriel\'s Robe',
    'Strength Beyond Strength',
    'Goetia Plate',
    'Khazra Plate',
    'Skull of the Viz-Jaq\'taar',
    'Reapers',
    'Veil of Steel',
    'Undead Crown',
    'Dark Pact',
    'Soulsplitter',
    'Radiance',
    'Griffon\'s Eye',
    'Idol of Rygnar',
    'Black Masquerade',
    'The Flying Saucer',
    'Stormflyer',
    'Madawc Val Narian',
    'The Collector',
    'Celestial Barrier',
    'Lunar Eclipse',
    'Dementia',
    'Black Void',
    'Champion of the Triune',
    'Demonic Touch',
    'Rogue Foresight',
    'Facebreaker',
    'Lorekeeper',
    'Lamha Na Draoithe',
    'Spirit Walker',
    'Angel\'s Wrath',
    'Akarat\'s Trek',
    'Knight\'s Grace',
    'Rakkis\' Benediction',
    'Rainbow Maiden',
    'Deviant Crown',
    'Asgardsreia',
    'Danmaku',
    'Crimson Dream',
    'Hammerfall',
    'Eternal Bodyguard',
    'Zayl\'s Temptation',
    'Pawnstorm',
    'The Ancients\' Legacy',
    'Warmonger',
    'Voice of Arreat',
    'Boarfrost',
    'Lilith\'s Legion',
    'Greenwalker\'s Charge',
    'Sky Spirit',
    'Ranger\'s Disguise',
    'Homunculus',
    'Feardrinker',
    'The Sentinel\'s Sorrow',
    'Sinwar',
    'Blessed Wrath',
    'Veil of the Tainted Sun',
    'Mark of the Que-Hegan',
    'The Vanquisher',
    'The Last Crusader',
    'Herald of Zakarum',
    'Angelhost',
    'Cloak of the Outcast',
    'Adamantine Guard',
    'Frozen Heart',
    'Lachdanan\'s Visage',
    'Atanna Khan\'s Dress',
    'The Eviscerator',
    'Sherazade',
    'Alnair',
    'Sarandeshi Hellcaller',
    'Eternal Vigil',
    'Astral Blade',
    'Durandal the Blazing Sword',
    'Shadowfang',
    'Carsomyr',
    'The Grandfather',
    'Headsman',
    'The Colonel',
    'Dux Infernum',
    'Gotterdammerung',
    'Hammer of Jholm',
    'Solar Scion',
    'The Redeemer',
    'Battlemaiden',
    'Vizjerei Fury',
    'Moonfang',
    'Heartseeker',
    'The Retiarius',
    'Stormchaser',
    'Freakshow',
    'Wizardspike',
    'Black Razor',
    'Drow Valor',
    'Dark Nemesis',
    'Piranha Swarm',
    'Penumbra',
    'Deckard Cain\'s Heirloom',
    'Staff of Shadows',
    'Spire of Sarnakyle',
    'Absolute Zero',
    'Valthek\'s Command',
    'Etrayu',
    'Signal Fire',
    'Windforce',
    'Buriza-Do Kyanon',
    'Manticore Sting',
    'Athulua\'s Wrath',
    'Chasmstriker',
    'Panthera\'s Bite',
    'Titan\'s Revenge',
    'Sagittarius',
    'Mind Rake',
    'Zular Khan\'s Tempest',
    'Gladiator\'s Rage',
    'Berserrker',
    'Claw of the Spirit Wolf',
    'Colliding Fury',
    'Thunder King of Sescheron',
    'The King of Ents',
    'Eye of the Storm',
    'Mr. Painless',
    'The Biting Frost',
    'Soul Reaver',
    'Shadowfiend',
    'The Defiler',
    'Heart of Fire',
    'Advent of Hatred',
    'Stygian Fury',
    'Mad King\'s Spine',
    'Adjudicator',
    'The Angiris Star',
    'Malleus Maleficarum',
    'Venom Sting',
    'Jaguar\'s Grasp',
    'Holy Wars',
    'Mistress of Pain',
    'Glowing Vertigo',
    'Atanna\'s Key',
    'Galeona\'s Lash',
    'Steel Punisher',
    'Despondence',
    'Smokeless Fire',
    'Malevolence'
]

SSSU_ITEMS = [
    'Tyrael\'s Might',
    'Azurewrath',
    'The Point of No Return',
    'Storm Blade',
    'The Searing Heat',
    'Desolation',
    'The Worshipper'
]

SETS = {
  'Fire': 'Pantheon',
  'Earth': 'Pantheon',
  'Heaven': 'Pantheon',
  'Water': 'Pantheon',
  'Frost': 'Pantheon',
  "Vasily's Falling Star": "Vasily's Following",
  "Vasily's Eclipse": "Vasily's Following",
  "Vasily's Shepherd Moon": "Vasily's Following",
  "Vasily's Crescent": "Vasily's Following",
  "Vasily's Moonwalkers": "Vasily's Following",
  "Red Vex' Flayer": "Red Vex' Embrace",
  "Red Vex' Idol": "Red Vex' Embrace",
  "Red Vex' Mantle": "Red Vex' Embrace",
  "Red Vex' Curse": "Red Vex' Embrace",
  "Red Vex' Sin": "Red Vex' Embrace",
  "Zerae's Holy Wrath": "Zerae's Divinity",
  "Zerae's Redemption": "Zerae's Divinity",
  "Zerae's Vindication": "Zerae's Divinity",
  "Zerae's Refinement": "Zerae's Divinity",
  "Zerae's Blessing": "Zerae's Divinity",
  "Celestia's Passion": "Celestia's Myth",
  "Celestia's Wings": "Celestia's Myth",
  "Celestia's Glory": "Celestia's Myth",
  "Celestia's Ribbon": "Celestia's Myth",
  "Celestia's Charge": "Celestia's Myth",
  "Vizjun's Science": "Vizjun's Devices",
  "Vizjun's Monitor": "Vizjun's Devices",
  "Vizjun's Engine": "Vizjun's Devices",
  "Vizjun's Foresight": "Vizjun's Devices",
  "Vizjun's Progress": "Vizjun's Devices",
  'Killing Vector': 'Universal Law',
  'Hypersurface': 'Universal Law',
  'World Line': 'Universal Law',
  'Dead Lens': 'Universal Law',
  'Quantum Bevel': 'Universal Law',
  "Tracker's Strike": 'Creed',
  "Tracker's Effigy": 'Creed',
  "Tracker's Stealth": 'Creed',
  "Tracker's Totem": 'Creed',
  "Tracker's Runeward": 'Creed',
  "Witchhunter's Fire": "Witchhunter's Attire",
  "Witchhunter's Crucifix": "Witchhunter's Attire",
  "Witchhunter's Faith": "Witchhunter's Attire",
  "Witchhunter's Hood": "Witchhunter's Attire",
  "Witchhunter's Rope": "Witchhunter's Attire",
  "Serpent's Fangs": 'The Snake Pit',
  "Serpent's Scales": 'The Snake Pit',
  "Serpent's Tongue": 'The Snake Pit',
  "Serpent's Coil": 'The Snake Pit',
  "Serpent's Tail": 'The Snake Pit',
  'Eruption': 'Mount Arreat',
  'Snowstorm': 'Mount Arreat',
  'Avalanche': 'Mount Arreat',
  'Ravine': 'Mount Arreat',
  'Rockslide': 'Mount Arreat',
  "Hunter's Claw Fist": 'Big Game Hunter',
  "Hunter's Camouflage": 'Big Game Hunter',
  "Hunter's Skin": 'Big Game Hunter',
  "Hunter's Trophy": 'Big Game Hunter',
  "Hunter's Trackless Step": 'Big Game Hunter',
  'Sacred Charge': 'Spirits of the Nephalem',
  'Destiny': 'Spirits of the Nephalem',
  'The Guardian': 'Spirits of the Nephalem',
  'The Protector': 'Spirits of the Nephalem',
  'The Defender': 'Spirits of the Nephalem',
  'The Coming Storm': 'Gathering of the Tribes',
  "Bear's Warding": 'Gathering of the Tribes',
  "Wolf's Fang": 'Gathering of the Tribes',
  "Snake's Battle Chant": 'Gathering of the Tribes',
  "Crane's Reach": 'Gathering of the Tribes',
  'Vale Hunter': 'Tundra Walker',
  'Grey Ranger': 'Tundra Walker',
  'Snow Silver': 'Tundra Walker',
  'Ancient Bronze': 'Tundra Walker',
  'Steppe Sleeper': 'Tundra Walker',
  "Nature's Wrath": 'Caoi Dulra',
  "Nature's Will": 'Caoi Dulra',
  "Nature's Vigil": 'Caoi Dulra',
  "Nature's Embrace": 'Caoi Dulra',
  "Nature's Grasp": 'Caoi Dulra',
  "Lone Wolf's Maul": "Lone Wolf's Path",
  "Lone Wolf's Fur": "Lone Wolf's Path",
  "Lone Wolf's Gaze": "Lone Wolf's Path",
  "Lone Wolf's Claws": "Lone Wolf's Path",
  "Lone Wolf's Track": "Lone Wolf's Path",
  "Scosglen's Myths": 'Last King of Scosglen',
  "Scosglen's Fables": 'Last King of Scosglen',
  "Scosglen's Tales": 'Last King of Scosglen',
  "Scosglen's History": 'Last King of Scosglen',
  "Scosglen's Legends": 'Last King of Scosglen',
  'Emerald Flower': 'Rainbow Warrior',
  'Emerald Earth': 'Rainbow Warrior',
  'Emerald Cloud': 'Rainbow Warrior',
  'Emerald Sky': 'Rainbow Warrior',
  'Emerald Growth': 'Rainbow Warrior',
  "Marchosias' Anger": "Marchosias' Essence",
  "Marchosias' Deception": "Marchosias' Essence",
  "Marchosias' Evil Grin": "Marchosias' Essence",
  "Marchosias' Might": "Marchosias' Essence",
  "Marchosias' Hatred": "Marchosias' Essence",
  'Femur of the Prophet': 'Celestial Orchard',
  'The Dragon Grave': 'Celestial Orchard',
  "Giyua's Sacrum": 'Celestial Orchard',
  'The Trickster': 'Celestial Orchard',
  'Lirian Moon': 'Celestial Orchard',
  "Lazarus' Lamen": 'Archbishop Lazarus',
  "Lazarus' Votive Lamp": 'Archbishop Lazarus',
  "Lazarus' Surplice Cap": 'Archbishop Lazarus',
  "Lazarus' Chasuble": 'Archbishop Lazarus',
  'Archangel Dark Angel': 'Satanic Mantra',
  'Lend Me Thy Light': 'Satanic Mantra',
  "Through Death's Veil": 'Satanic Mantra',
  'Till We Have': 'Satanic Mantra',
  'Heaven In Sight': 'Satanic Mantra',
  "Achilios' Sledgehammer": "Achilios' Wake",
  "Achilios' Refuge": "Achilios' Wake",
  "Achilios' Eagle Eye": "Achilios' Wake",
  "Achilios' Knuckledusters": "Achilios' Wake",
  "Achilios' Stealth": "Achilios' Wake",
  "Rathma's Tyranny": "Rathma's Empire",
  "Rathma's Skeleton": "Rathma's Empire",
  "Rathma's Death Gaze": "Rathma's Empire",
  "Rathma's Trap": "Rathma's Empire",
  "Rathma's Chase": "Rathma's Empire",
  'Tower Rush': 'The Towerlord',
  'Tower Defense': 'The Towerlord',
  'Tower Wall': 'The Towerlord',
  'Tower Denial': 'The Towerlord',
  'Tower Push': 'The Towerlord',
  "Yaerius' Xyston": "Yaerius' Grey Omen",
  "Yaerius' Simulacrum": "Yaerius' Grey Omen",
  "Yaerius' Untruth": "Yaerius' Grey Omen",
  "Yaerius' Alembic": "Yaerius' Grey Omen",
  "Yaerius' Mediation": "Yaerius' Grey Omen",
  "Malthael's Wrath": "Malthael's Sanctuary",
  "Malthael's Halo": "Malthael's Sanctuary",
  "Malthael's Crown": "Malthael's Sanctuary",
  "Malthael's Ward": "Malthael's Sanctuary",
  "Malthael's Stride": "Malthael's Sanctuary",
  "Hadriel's Avenger": "Hadriel's Lore",
  "Hadriel's Pure Heart": "Hadriel's Lore",
  "Hadriel's Wings": "Hadriel's Lore",
  "Hadriel's Courage": "Hadriel's Lore",
  "Hadriel's Presence": "Hadriel's Lore",
  "Imperius' Sky Hammer": "Imperius' Edict",
  "Imperius' Radiance": "Imperius' Edict",
  "Imperius' Aura": "Imperius' Edict",
  "Imperius' Crusade": "Imperius' Edict",
  "Imperius' Winged Feet": "Imperius' Edict",
  "Cinadide's Malus": "Cinadide's Craft",
  "Cinadide's Forge": "Cinadide's Craft",
  "Cinadide's Bellows": "Cinadide's Craft",
  "Cinadide's Anvil": "Cinadide's Craft",
  "Cinadide's Bender": "Cinadide's Craft",
  'Witchblade': 'The Mysteries',
  'Cauldron': 'The Mysteries',
  'Pentacle': 'The Mysteries',
  'Sacred Circle': 'The Mysteries',
  'Charge of the Goddess': 'The Mysteries',
  "Warmage's Fireblade": 'The Warmage',
  "Warmage's Flameshroud": 'The Warmage',
  "Warmage's Breath": 'The Warmage',
  "Warmage's Conjuration": 'The Warmage',
  "Warmage's Wake": 'The Warmage',
  'Elemental Storm': 'Elemental Children',
  'Elemental Fury': 'Elemental Children',
  'Elemental Clash': 'Elemental Children',
  'Elemental Spirit': 'Elemental Children',
  'Elemental Trance': 'Elemental Children',
  "Zann Esu's Charm": "Zann Esu's Secrets",
  "Zann Esu's Binding Circle": "Zann Esu's Secrets",
  "Zann Esu's Robes": "Zann Esu's Secrets",
  "Zann Esu's Mysteries": "Zann Esu's Secrets",
  "Zann Esu's Rune Loop": "Zann Esu's Secrets",
  'Monad': "Adria's Circle",
  'Dyad': "Adria's Circle",
  'Triad': "Adria's Circle",
  'Tetrad': "Adria's Circle",
  'Pentad': "Adria's Circle",
  'Apefoot': 'Testament of the Apes',
  'Apehand': 'Testament of the Apes',
  'Apeskull': 'Testament of the Apes',
  'Apeskin': 'Testament of the Apes',
  'Apeshoot': 'Testament of the Apes',
  'Fangskin Scales': 'Henchmen Trophies',
  "Stareye's Claws": 'Henchmen Trophies',
  'Doomcloud Spine': 'Henchmen Trophies',
  "Blackskull's Horns": 'Henchmen Trophies',
  'Bilefroth Skin': 'Henchmen Trophies',
  "Geleb's Greed": 'Curse of the Zakarum',
  "Bremm's Retribution": 'Curse of the Zakarum',
  "Maffer's Frenzy": 'Curse of the Zakarum',
  "Wyand's Perfidy": 'Curse of the Zakarum',
  "Ismail's Majesty": 'Curse of the Zakarum'
}

RINGS = [
    'Ras Algethi',
    'Seal of the Nephalem Kings',
    'Ouroboros',
    'Bad Mood',
    'Signet of the Gladiator',
    'Sigil of the 7 Deadly Sins',
    'Ring of Disengagement',
    'Xorine\'s Ring',
    'The Seal of Kharos',
    'Sigil of Tur Dulra',
    'Giant\'s Knuckle',
    'Empyrean Glory',
    'Elemental Band',
    'Ring of Truth',
    'Earth Rouser',
    'Bloodbond',
    'Der Nebelring',
    'Witchcraft',
    'Adrenaline Rush',
    'Black Hand Sigil',
    'Ripstar',
    'Empyrean Band',
    'Myokai\'s Path',
    'Ring of Regha',
    'Assur\'s Bane'
]

AMULETS = [
    'Niradyahk',
    'Vizjerei\'s Necklace',
    'Dyers Eve',
    'In For The Kill',
    'Lamen of the Archbishop',
    'Hangman',
    'Felblood',
    'The Dreamcatcher',
    'Locket of Dreams',
    'Black Dwarf',
    'Death Ward',
    'Gallowlaugh',
    'Khanduran Royal Pendant',
    'Fren Slairea',
    'Angel Heart',
    'Teganze Pendant',
    'The Tesseract',
    'Klaatu Barada Nikto',
    'Beads of the Snake Queen',
    'Quov Tsin\'s Talisman',
    'The Buried Hawk',
    'Scarab of Death',
    'Athulua\'s Oracle',
    'Witchmoon',
    'Jerhyn\'s Tawiz'
]

JEWELS = [
    'Heavenstone',
    'Arkenstone',
    'Atomus',
    'The Boulder',
    'Demonstone Blood',
    'Katamari',
    'Xepera Xeper Xeperu',
    'Inarius\' Rock',
    'Cornerstone of the World',
    'Storm Shard',
    'Zakarum Stoning Rock',
    'Borgin\'s Vigil',
    'Zann Esu\'s Stone',
    'Suicide Note',
    'Jewel of Luck',
    'Asheara\'s Cateye',
    'Farsight Globe',
    'Wishmaster'
]

QUIVERS = [
    'Bag of Tricks',
    'Locust Hive',
    'Lammergeier',
    'Plague Gland',
    'Kingsport\'s Signals',
    'Cindercone',
    'Devil\'s Dance',
    'Larzuk\'s Bandolier',
    'Hanabigami',
    'The Tranquilizer'
]

MOS = [
    'Larzuk\'s Round Shot',
    'Vizjun\'s Ball Bearing',
    'Nor Tiraj\'s Flaming Sphere',
    'The Demon Core',
    'Uldyssian\'s Spirit',
    'Orb of Annihilation',
    'Warbringer',
    'Ten Pin Striker',
    'Wrathspirit',
    'Idol of Stars',
    'Nagapearl',
    'The Moon Crystal',
    'Auriel\'s Focus',
    'Solitude',
    'Crystal of Tears',
    'Essence of Itherael',
    'Periapt of Life',
    'Lodestone',
    'Kara\'s Trinket',
    'Monsterball',
    'Heart of Frost',
    'Relic of Yaerius',
    'The Endless Light',
    'Explorer\'s Globe',
    'The Perfect Sphere',
    'Marksman\'s Eye',
    'Zayl\'s Soul Orb',
    'Farnham\'s Lost Marble',
    'Eye of Malic',
    'Apple of Discord'
]

CHARMS = [
    'Sunstone of the Twin Seas',
    'Sacred Sunstone',
    'Shadow Vortex',
    'Worldstone Orb',
    'Caoi Dulra Fruit',
    'Soulstone Shard',
    'Eye of Divinity',
    'Nexus Crystal',
    'The Butcher\'s Tooth',
    'Optical Detector',
    'Laser Focus Crystal',
    'Sacred Worldstone Key',
    'Scroll of Kings',
    'Visions of Akarat',
    'Moon of the Spider',
    'Horazon\'s Focus',
    'The Black Road',
    'Legacy of Blood',
    'Fool\'s Gold',
    'Spirit Trance Herb',
    'Idol of Vanity',
    'Azmodan\'s Heart',
    'Weather Control',
    'Silver Seal of Ureh',
    'Crystalline Flame Medallion',
    'Soul of Kabraxis',
    'Eternal Bone Pile',
    'The Book of Lies',
    'Dragon Claw',
    'The Ancient Repositories',
    'Xazax\'s Illusion',
    'Astrogha\'s Venom Stinger',
    'The Sleep',
    'Neutrality Pact',
    'Glorious Book of Median',
    'Rathma\'s Supremacy',
    'Vial of Elder Blood',
    'Six Angel Bag',
    'Hammer of the Taan Judges',
    'Zakarum\'s Ear',
    'Sunstone of the Gods',
    'Umbaru Treasure',
    'Corrupted Wormhole',
    'Demonsbane',
    'Lylia\'s Curse',
    'Cold Fusion Schematics'
]

TROPHIES = [
    'Akarat Trophy',
    'Black Road Trophy',
    'Astrogha Trophy',
    'Legacy of Blood Trophy',
    'The Lord of Sin Trophy',
    'Lord Aldric Jitan Trophy',
    'Archbishop Lazarus Trophy',
    'Viz-jun Trophy',
    'Cathedral of Light Trophy',
    'Quov Tsin Trophy',
    'Duncraig Trophy',
    'Rathma Square Trophy',
    'Judgement Day Trophy',
    'Tran Athulua Trophy',
    'Kingdom of Shadow Trophy',
    'Uldyssian Trophy',
    'Triune Trophy'
]

SHRINE_VESSELS = [
    'Creepy Vessel',
    'Sacred Vessel',
    'Quiet Vessel',
    'Hidden Vessel',
    'Tainted Vessel',
    'Ornate Vessel',
    'Fascinating Vessel',
    'Intimidating Vessel',
    'Weird Vessel',
    'Trinity Vessel',
    'Spiritual Vessel',
    'Eerie Vessel',
    'Enchanted Vessel',
    'Shimmering Vessel',
    'Magical Vessel',
    'Abandoned Vessel'
]

SHRINES = [
    'Creepy Shrine',
    'Sacred Shrine',
    'Quiet Shrine',
    'Hidden Shrine',
    'Tainted Shrine',
    'Ornate Shrine',
    'Fascinating Shrine',
    'Intimidating Shrine',
    'Weird Shrine',
    'Trinity Shrine',
    'Spiritual Shrine',
    'Eerie Shrine',
    'Enchanted Shrine',
    'Shimmering Shrine',
    'Magical Shrine',
    'Abandoned Shrine'
]

VESSEL_TO_SHRINE = {
    'Creepy Vessel': 'Creepy Shrine',
    'Sacred Vessel': 'Sacred Shrine',
    'Quiet Vessel': 'Quiet Shrine',
    'Hidden Vessel': 'Hidden Shrine',
    'Tainted Vessel': 'Tainted Shrine',
    'Ornate Vessel': 'Ornate Shrine',
    'Fascinating Vessel': 'Fascinating Shrine',
    'Intimidating Vessel': 'Intimidating Shrine',
    'Weird Vessel': 'Weird Shrine',
    'Trinity Vessel': 'Trinity Shrine',
    'Spiritual Vessel': 'Spiritual Shrine',
    'Eerie Vessel': 'Eerie Shrine',
    'Enchanted Vessel': 'Enchanted Shrine',
    'Shimmering Vessel': 'Shimmering Shrine',
    'Magical Vessel': 'Magical Shrine',
    'Abandoned Vessel': 'Abandoned Shrine'
}

IGNORED_ITEMS = [
    'Apple',
    'Horadric Cube',
    'Minor Healing Potion',
    'Light Healing Potion',
    'Healing Potion',
    'Greater Healing Potion',
    'Super Healing Potion',
    'Minor Mana Potion',
    'Light Mana Potion',
    'Mana Potion',
    'Greater Mana Potion',
    'Super Mana Potion',
    'Rejuvenation Potion',
    'Full Rejuvenation Potion',
    'Ring',
    'Amulet',
    'Catalyst of Disenchantment',
    'Catalyst of Learning',
    'Signet of Gold',
    'Greater Signet of Gold',
    'Large Axe (1)',
    'Quilted Armor (1)',
    'Buckler (1)',
    'Hand Axe (1)',
    'Javelin (1)',
    'Katar (1)',
    'Short Staff (1)',
    'Short Sword (1)',
    'Wand (1)'
]

RUNEWORDS = [
  'Dawn',
  'Shark',
  'Enyo',
  'Azrael',
  'Void',
  'Oblivion',
  'Berith',
  'Gehenna',
  'Triune',
  'Adramelech',
  'Archangel',
  'Shattered Stone',
  'Banshee',
  'Amok',
  'Shockwave',
  'Hornet',
  'Balance',
  'Nyx',
  'Hive',
  'Phantom',
  'Curse',
  'Typhaon',
  'Stardust',
  'Dead Man\'s Breath',
  'Thammuz',
  'Python',
  'Cyclops',
  'Tynged',
  'Tartarus',
  'Araboth',
  'Tombstone',
  'Faseroptic',
  'Urada',
  'Minefield',
  'Instinct',
  'Sabertooth',
  'Midas\' Touch',
  'Myrmidon',
  'Asymptomatic',
  'Endor',
  'Atlacamani',
  'Seed of Conflict',
  'Solarion',
  'King\'s Blood',
  'Rattus',
  'Malicicle',
  'Demhe',
  'Arachnophilia',
  'Calypso',
  'Neurogenesis',
  'Pax Mystica',
  'Hadad',
  'Summanus',
  'Akhenaten',
  'Ljosalf',
  'Aes Dana',
  'Elverfolk',
  'Erilaz',
  'Zodiac',
  'Kyrie',
  'Hand of Frost',
  'Prophecy',
  'Bane',
  'Judas',
  'Path',
  'Jokulmorder',
  'Gabriel',
  'Durga',
  'Galdr',
  'Apostasy',
  'Oris\' Herald',
  'Raid',
  'Hastata',
  'Haste',
  'Hastilude',
  'Hastur',
  'Hastin',
  'Fleshbane',
  'Patriot',
  'Chrysopelea',
  'Dajjal',
  'Quantum',
  'Myriad',
  'Naiad',
  'Burlesque',
  'Tau',
  'Dead Star',
  'Cheetah',
  'Fennec',
  'Manitou',
  'Raptor',
  'Thundercloud',
  'Kodiak',
  'Dragon Seed',
  'Aspect',
  'Corsair',
  'Ice Breaker',
  'Eris',
  'Colliding Worlds',
  'Manta',
  'Cecaelia',
  'Arnazeus Pinnacle',
  'Aegina',
  'Titanomachia',
  'Sankara',
  'Rusalka',
  'Evanescence',
  'Freybug',
  'Flame',
  'Scar',
  'Firefly',
  'Trishula',
  'Herfjotur',
  'Stalactite',
  'Specter',
  'Askari Device',
  'Shedim',
  'Carabosse',
  'Fiend',
  'Riot',
  'Judge',
  'Choronzon',
  'Anarchy',
  'Hail',
  'Nahemah',
  'Joker',
  'Perfection',
  'Khattak',
  'Shamo',
  'Hieros Gamos',
  'Lataif-as-Sitta',
  'Oniwaka',
  'Blooddancer',
  'Ram',
  'Essus',
  'Thunderbird',
  'Gharaniq',
  'Savitr',
  'Skarn',
  'Anak',
  'Khan',
  'Lahmu',
  'Kahless',
  'Gilgamesh',
  'El\'druin',
  'Wolfsangel',
  'Soldier of Light',
  'Peacock',
  'Lynx',
  'Sylvanshine',
  'Tarqeq',
  'Cernunnos',
  'Raudna',
  'Dirge',
  'Amphibian',
  'Ocean',
  'Samhain',
  'Augur',
  'Lincos',
  'Laadan',
  'Lojban',
  'Loxian',
  'Hermanubis',
  'Fiacla-Gear\'s Weathervane',
  'Black Cat',
  'Mantra',
  'Lemuria',
  'Chthon',
  'Eventide',
  'Inti',
  'Leviathan',
  'Tzeentch',
  'Bartuc\'s Eye',
  'Loa',
  'Jinx',
  'Misery',
  'Seid',
  'Roc',
  'Mkodos',
  'Cut',
  'Deep Water',
  'Eurynome',
  'Ladon',
  'Hali',
  'Dagda',
  'Santa Compana',
  'Styx',
  'Xazax',
  'Koan',
  'Ghoul',
  'Dead Ringer',
  'Ngozi',
  'Semhazai',
  'Krypteia',
  'Doomguard',
  'Genie',
  'Atlantis',
  'Aether',
  'Crucible',
  'Kronos',
  'Rhea',
  'Force of Mind',
  'Ensi',
  'Nehushtan',
  'Resheph',
  'Taqiyya',
  'Orisha',
  'Rex Deus',
  'Jaguar',
  'Hadriel\'s Protector',
  'Jihad',
  'Intifada',
  'Lammasu',
  'Quaoar',
  'Takfir',
  'Brahman',
  'Oriflamme',
  'Skilt en Vriend',
  'Judgement',
  'Circe',
  'Ker',
  'Vertigo',
  'Gravastar',
  'Kabbalah',
  'Hestia',
  'Kallisti',
  'Sauron',
  'Helgrotha',
  'Inanna',
  'Brocken',
  'Grace',
  'Khany',
  'Shaula',
  'Sway of the Stars',
  'Dark Exile',
  'Rebel',
  'Lumen Arcana',
  'Paaliaq',
  'Victory\n(Median XL - 6 years)',
  'Thelema',
  'Cathedral',
  'Mirage',
  'Dragonheart',
  'Erawan',
  'Unity',
  'Linga Sharira',
  'Pygmalion',
  'Eternal\nMedian 2005-2012\nThanks everyone!',
  'Hellfire Plate',
  'Summit',
  'Cannonball',
  'Ra',
  'Alchemy',
  'Dreadlord',
  'Bogspitter',
  'Eidolon',
  'Amanita',
  'Thundercap',
  'Checkmate',
  'Sphinx',
  'Lily',
  'Eulenspiegel',
  'Wintermute',
  'Indigo',
  'Rathma\'s Blessing',
  'Geas',
  'Pharaoh',
  'Nomad',
  'Goddess',
  'Kodo',
  'Wall of Fire',
  'Avatar',
  'Derweze',
  'Khalim\'s Protector',
  'Rainbow',
  'Prodigy',
  'Fuse',
  'Pulsa Dinura',
  'Truce',
  'Dyaus Pita',
  'Ahriman',
  'Nero',
  'Lysra',
  'Iblis',
  'Mercy',
  'Brawl',
  'Kali',
  'Aiwass',
  'Skald',
  'Icarus',
  'Drekavac',
  'Snowsquall',
  'Retribution',
  'Knave',
  'Epicenter',
  'Outlaw',
  'Ginfaxi',
  'Craton',
  'Megalith',
  'Nephilim',
  'Hibagon',
  'Riptide',
  'Wind Runner',
  'Stata Mater',
  'Bona Dea',
  'Amaterasu',
  'Siegfried',
  'Cambion',
  'Lohengrin',
  'Unicorn',
  'Shaheeda',
  'Eaglehorn Mask',
  'Edda',
  'Lion',
  'Eloi',
  'Nix',
  'Ea',
  'Eos',
  'Heart of Skovos',
  'Afrit',
  'Rahab',
  'Iambe',
  'Ligeia',
  'Dar-Al-Harb',
  'Scorched Earth',
  'Orchid',
  'Shadowsteps',
  'Algiz',
  'Nasrudin',
  'Ekam',
  'Fawkes',
  'Sagarmatha',
  'Morthwyrtha',
  'Wodziwob',
  'Greisen',
  'Force Shock',
  'Enmerkar',
  'Warpath',
  'Gauntlet',
  'Huracan',
  'E-Engur-A',
  'Tonatiuh',
  'Triune\'s Blessing',
  'Aegipan',
  'Nezha',
  'Natha',
  'Norma',
  'Grove',
  'Slyph',
  'Nigra',
  'Nature\'s Grace',
  'Cube',
  'Warlock',
  'Nahual',
  'Lorelei',
  'Quimbanda',
  'Wyrm',
  'Hecatomb',
  'Twisted Mind',
  'Ilmatar',
  'Hierodule',
  'Crusade',
  'Surya',
  'Malakbel',
  'Rotundjere',
  'Battle Rage',
  'Asmodai',
  'Sangreal',
  'Zohar',
  'Asclepion',
  'Amaymon',
  'Myrrhbearer',
  'Lightwell',
  'Lyrannikin',
  'Kundalini',
  'Demeter',
  'Curandera',
  'Astarte',
  'Oracle',
  'Vanity',
  'Comaetho',
  'Venefica',
  'Cassilda',
  'Space Dementia',
  'Dawn',
  'Shark',
  'Enyo',
  'Azrael',
  'Void',
  'Banshee',
  'Amok',
  'Shockwave',
  'Hornet',
  'Balance',
  'Nyx',
  'Hive',
  'Thammuz',
  'Python',
  'Cyclops',
  'Instinct',
  'Myrmidon',
  'Endor',
  'King\'s Blood',
  'Demhe',
  'Pax Mystica',
  'Hadad',
  'Summanus',
  'Akhenaten',
  'Ljosalf',
  'Prophecy',
  'Bane',
  'Judas',
  'Path',
  'Raid',
  'Hastata',
  'Haste',
  'Patriot',
  'Chrysopelea',
  'Dajjal',
  'Quantum',
  'Cheetah',
  'Fennec',
  'Manitou',
  'Aspect',
  'Corsair',
  'Ice Breaker',
  'Aegina',
  'Titanomachia',
  'Scar',
  'Firefly',
  'Shedim',
  'Carabosse',
  'Fiend',
  'Riot',
  'Judge',
  'Khattak',
  'Shamo',
  'Ram',
  'Essus',
  'Thunderbird',
  'Gharaniq',
  'Peacock',
  'Lynx',
  'Sylvanshine',
  'Ocean',
  'Samhain',
  'Augur',
  'Lincos',
  'Black Cat',
  'Mantra',
  'Lemuria',
  'Chthon',
  'Loa',
  'Jinx',
  'Misery',
  'Deep Water',
  'Eurynome',
  'Ladon',
  'Koan',
  'Ghoul',
  'Genie',
  'Atlantis',
  'Aether',
  'Ensi',
  'Nehushtan',
  'Resheph',
  'Jihad',
  'Intifada',
  'Lammasu',
  'Quaoar',
  'Circe',
  'Ker',
  'Vertigo',
  'Gravastar',
  'Inanna',
  'Brocken',
  'Rebel',
  'Lumen Arcana',
  'Paaliaq',
  'Victory\n(Median XL - 6 years)',
  'Thelema',
  'Cathedral',
  'Mirage',
  'Natasha\'s Legacy',
  'Summit',
  'Cannonball',
  'Ra',
  'Alchemy',
  'Sphinx',
  'Lily',
  'Geas',
  'Pharaoh',
  'Nomad',
  'Goddess',
  'Rainbow',
  'Prodigy',
  'Fuse',
  'Iblis',
  'Mercy',
  'Brawl',
  'Kali',
  'Aiwass',
  'Epicenter',
  'Outlaw',
  'Ginfaxi',
  'Craton',
  'Stata Mater',
  'Bona Dea',
  'Amaterasu',
  'Siegfried',
  'Edda',
  'Afrit',
  'Rahab',
  'Iambe',
  'Ligeia',
  'Algiz',
  'Nasrudin',
  'Ekam',
  'Fawkes',
  'Enmerkar',
  'Warpath',
  'Aegipan',
  'Nezha',
  'Natha',
  'Cube',
  'Warlock',
  'Ilmatar',
  'Hierodule',
  'Asmodai',
  'Sangreal',
  'Zohar',
  'Lyrannikin',
  'Kundalini',
  'Demeter',
  'Curandera'
]

ORANGE_IGNORED_ITEMS = [
    'Emblem of Destruction',
    'Emblem of Hatred',
    'Emblem of Lies',
    'Emblem of Pain',
    'Emblem of Suffering',
    'Emblem of Terror',
    'Mark of Infusion',
    'Belladonna Extract',
    'Ancient Book',
    'Cycle',
    'Oil of Conjuration',
    'Sunless Crystal Bird'
]

TRADE_POST_SETS_SECTION = '''[color=#00FF00][size=24]Sets[/size][/color]
[hr][/hr]
{items}'''

TRADE_POST_SU_SECTION = '''[color=#804000][size=24]SU[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_SSU_SECTION = '''[color=#804000][size=24]SSU[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_SSSU_SECTION = '''[color=#804000][size=24]SSSU[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_RUNEWORDS_SECTION = '''[color=#808080][size=24]Runewords[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_RAQMOJ_SECTION = '''[color=#804000][size=24]Rings/Amulets/Quivers/MOs/Jewels[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_BASES_SECTION = '''[color=#808080][size=24]Bases[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_CHARMS_SECTION = '''[color=#FF7F50][size=24]Charms[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_TROPHIES_SECTION = '''[color=#FFA500][size=24]Trophies[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_MISC_SECTION = '''[color=#FFFFFF][size=24]Misc[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_CRAFTED_SECTION = '''[color=#CD853F][size=24]Crafted[/size][/color]
[hr][/hr]
{items}
'''

TRADE_POST_TEMPLATE = '''[color=#FFFF00][size=26]Selling[/size][/color]
[hr][/hr]
{items}
'''
